export const BASE_URL = 'https://admin.globexhup.com/api/v1';

export const ENDPOINTS = {
  HOME: '/home',
  PROJECTS_PAGE: '/projects-page',
  SERVICES_PAGE: '/services-page',
  STRATEGY_PAGE: '/strategy-page',
  BLOGS_PAGE: '/blogs-page',
  ABOUT: '/about',
  SEARCH: '/search',
  BLOGS: '/blogs',
  SERVICES: '/services',
  PROJECTS: '/projects',
  CONTACT_PAGE: '/contact-page',
  CONTACT_SEND: '/contact/send',
  CONTACT: '/contact',
  VENDOR_REGISTER: '/vendors/register',
  VENDOR_PAGE: '/vendors/page',
  VENDOR_OPTIONS: '/vendors/options',
  VENDOR_STATUS: (ref) => `/vendors/${ref}/status`,
  SUPPLIER_REGISTER: '/suppliers/register',
  SETTINGS: '/settings',
  AUTH_ME: '/auth/me',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_GOOGLE: '/auth/google',
};
